[project]
name = "langgraph-agent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.0",
    "langchain[anthropic]>=0.3.27",
    "langgraph>=0.5.4",
    "python-dotenv>=1.1.1",
]
